// @ts-check
import withNuxt from './.nuxt/eslint.config.mjs';

export default withNuxt({
    rules: {
        'max-len': 'off',
        'no-console': 'off',
        indent: 'off',
        'comma-dangle': 'off',
        'vue/multi-word-component-names': 'off',
        'object-curly-spacing': 'off',
        'object-curly-newline': 'off',
        'operator-linebreak': 'off',
        '@typescript-eslint/explicit-member-accessibility': 'error',
        'arrow-parens': 'off',
        'import/no-unresolved': 'off',
        'import/prefer-default-export': 'off',
        'import/extensions': 'off',
        'class-methods-use-this': 0,
        'function-paren-newline': 'off',
        'func-call-spacing': 'off',
        'lines-between-class-members': [
            'error',
            'always',
            {
                exceptAfterSingleLine: true,
            },
        ],
        'no-empty-function': 'off',
        'no-plusplus': [
            'error',
            {
                allowForLoopAfterthoughts: true,
            },
        ],
        'no-unused-vars': 'off',
        'no-useless-constructor': 'off',
        'no-param-reassign': 'off',
        'no-shadow': 'off',
        'no-useless-escape': 'off',
        'no-use-before-define': [
            'error',
            {
                variables: true,
                functions: false,
                classes: false,
            },
        ],
        'space-before-blocks': 'error',
        'space-before-function-paren': 'off',
        'comma-style': 'error',
        'dot-notation': 'off',
        'no-void': 'off',
        semi: 'error',
        quotes: [
            'error',
            'single',
            {
                allowTemplateLiterals: true,
                avoidEscape: true,
            },
        ],
        yoda: 'off',
        'prefer-destructuring': [
            'error',
            {
                object: false,
                array: false,
            },
        ],
        'no-continue': 'off',
        'no-underscore-dangle': 'off',
        'no-extra-boolean-cast': 'off',
        'arrow-body-style': 'off',
        'no-restricted-globals': 'off',
        'new-cap': 'off',
        'no-restricted-properties': 'off',
        '@angular-eslint/no-input-rename': 'off',
        'consistent-return': 'off',
        'no-bitwise': 'off',
        'global-require': 'off',
        'vuejs-accessibility/label-has-for': 'off',
        'vue/html-self-closing': 'off',
        'vue/no-v-text-v-html-on-component': ['error', { allow: ['q-route-tab'] }],
        'vuejs-accessibility/form-control-has-label': 'off',
        'vuejs-accessibility/click-events-have-key-events': 'off',
        'import/no-extraneous-dependencies': 'off',
        'implicit-arrow-linebreak': 'off',
        '@typescript-eslint/no-empty-interface': 'off',
        '@typescript-eslint/no-explicit-any': 'off',
        'vue/no-dupe-keys': 'off',
        'vue/no-multiple-template-root': 'off',
        '@typescript-eslint/no-duplicate-enum-values': 'off',
        'vue/attribute-hyphenation': 'off',
        '@typescript-eslint/no-unused-vars': 'off',
    },
});
